### ISSUE TITLE
Distinction with the lichess analyzer

### ISSUE THREAD

**Issue by DaemonWoo** [gustavotoyota/ChessAnalyzer#1]
When i have pgn "1. e4" the analyzer suggests "e6" or "d4" with the greatest advantage, but on `lichess` it always suggests "2. e5", which i think is correct. Can i somehow tweak your analyzer to work exactly like lichess one?

**Comment by gustavotoyota** [comment]
I think Lichess uses precomputed data for the openings for better accuracy.
The engine in this project computes everything in real time.
We may need access to the raw Lichess opening database to replicate their analyzer.
